format_bundle := if os() == "windows" { "--format wxsmsi" } else { if os() == "linux" { "--format appimage" } else { "--format osx" }  }

# list available commands
list:
	just --list

make_win_icon:
    convert static/base_icon.png -define icon:auto-resize=16,24,32,48,64,128,256,512 static/icon.ico

create_mac_installer: bundle
    pkgbuild --install-location /Applications --component ../../target/release/bundle/osx/Rpack.app ../../target/release/bundle/osx/Rpack.pkg

# Create the installer using cargo-bundler
bundle:
    cargo bundler -r
